language: python

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      language: python
      python: "2.7_with_system_site_packages"
      env: PACKAGES="gir1.2-glib-2.0 gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0 gstreamer1.0-plugins-base python-gi python-gst-1.0" PYTHON="python"
    - os: linux
      sudo: required
      dist: trusty
      language: python
      python: "3.4_with_system_site_packages"
      env: PACKAGES="gir1.2-glib-2.0 gir1.2-gstreamer-1.0 gir1.2-gst-plugins-base-1.0 gstreamer1.0-plugins-base python3-gi python3-gst-1.0" PYTHON="python3"

install:
  - sudo apt-get update -q
  - sudo apt-get install --no-install-recommends -y $(echo $PACKAGES)
  - pip install tox-travis

script: tox
